apiVersion: apps/v1
kind: Deployment
metadata:
  name: contoso-air
  namespace: dev
spec:
  selector:
    matchLabels:
      app: contoso-air
  template:
    metadata:
      labels:
        app: contoso-air
    spec:
      containers:
      - name: contoso-air
        image: lampsonregistry.azurecr.io/image-workflow-1761858944473:e6644fb1b639a8fcbeaed65dd5cb5a574deaa4ff
        # ... existing ports/env/resources unchanged ...
        readinessProbe:
          httpGet:
            path: /
            port: 3000
            scheme: HTTP
          initialDelaySeconds: 2
          periodSeconds: 5
          failureThreshold: 3
        livenessProbe:
          httpGet:
            path: /
            port: 3000
            scheme: HTTP
          initialDelaySeconds: 60
          periodSeconds: 10
          failureThreshold: 3
        # startupProbe removed
