apiVersion: apps/v1
kind: Deployment
metadata:
  name: contoso-air
  namespace: dev
  labels:
    app.kubernetes.io/name: contoso-air
spec:
  replicas: 1
  progressDeadlineSeconds: 1800   # give more time while debugging (30 minutes)
  selector:
    matchLabels:
      app.kubernetes.io/name: contoso-air
  template:
    metadata:
      labels:
        app.kubernetes.io/name: contoso-air
    spec:
      serviceAccountName: default
      containers:
      - name: contoso-air
        # Use the image produced by CI. Update the tag for new builds.
        image: lampsonregistry.azurecr.io/image-workflow-1761858944473:b936d94d40c6cd1618d2dc34b1eb4846d5da9c4e
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 3000
        env:
        - name: PORT
          value: "3000"
        envFrom:
        - configMapRef:
            name: contoso-air-config
        resources:
          requests:
            cpu: 500m
            memory: 512Mi
          limits:
            cpu: 1
            memory: 1Gi
        # Relax or remove startupProbe while switching to prebuilt image.
        # Use a health endpoint that your app implements ("/health" or "/").
        startupProbe:
          httpGet:
            path: /health
            port: 3000
          initialDelaySeconds: 20
          timeoutSeconds: 5
          periodSeconds: 10
          failureThreshold: 30
        readinessProbe:
          httpGet:
            path: /health
            port: 3000
          initialDelaySeconds: 30
          periodSeconds: 10
        livenessProbe:
          httpGet:
            path: /health
            port: 3000
          initialDelaySeconds: 60
          periodSeconds: 20
